---
- hosts: web
  become: true
  become_method: su
  become_user: root
 # become_ask_pass: true
 # dodane
  tasks:
   - name: Update
     apt: update_cache=yes upgrade=dist cache_valid_time=3600
     notify: autoremove

  handlers:
      - name: autoremove
        apt: autoremove=yes

#- name: Upgrade

     #notify:  # Odnosi się do "name" w handlers - musi byc ta sama fraza
     #  - Upgrade

     #handlers:
     #- name: Upgrade
     #  apt: name=nginx state=restarted

